server.port = 8090

#LOGGING chi tiết
logging.level.root = INFO
logging.level.com.ou.LMS_Spring = DEBUG

spring.application.name=LMS_Spring
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/lms_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=C8mBQxpzu3LCmLQ.root
spring.datasource.password=wao8L1rPypJ1heCg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=and0c2VjcmV0a2V5X2xlYXJuaW5nbWFuYWdlbWVudHN5c3RlbV9odW5nX2toYW5oX2toYW5nXzIyNTEwNTIwNDBfMjI1MTA1MjA1MV8yMjUxMDUyMDQ5
jwt.expiration=3600000
jwt.issuer=LMS_Spring

# Cloudinary
cloudinary.cloud-name=delrpa4vp
cloudinary.api-key=448295678452768
cloudinary.api-secret=tCDOEADl_HbvJiHkx4IE6vHCb9s
cloudinary.folder=${CLOUDINARY_FOLDER:lms/avatars}